#
#  vim:ts=2:sw=2:et
#
env:
  global:
  - secure: SPjEJ+yo4V+BxmswdRBGLv+eRO9/TkhZRPud5z/Pu9n7jTv3V/0mL25nwnwyiFWv5ZTvR/nrYucZGa8gHbauVKTNad/scrO4pq4vooxLDJKrmRo36v4UFrLDhKuBYEAYzZU6fW9QJexU7EzOVnpXxlleb5BXH+zd8EIGOBVLxzUMznew8eekWH67ZkqtMCpiq04tuuZYiiJypxxvhdTnb97/VL66/FtwfKG06k0EgDFe3dsjIb47uQH73B20+SEZVrS1csdA5KcxcqSOPjX9M92DhF6ozkYNqhTNdQBag6N6h833aYZAOoZT+84PdlfmDHJdPI7fJqr8XRLsrnj4+v1r9CT6XFkR7HA7HVPksm1ZJ1w9qDvr6ucVCt6vXC3M4PG/2FgWvZjY4UT4fd18vhjSKHhz4F8qaz6qqYr+yOL0uC/uLijYCPq5ZzA32oiSZbEkbUKtL5KBVGWVKiAq7hMDT+mS/I/EyweFjI27bVa4LKPyPX2vLOI5NqsUtgAOOI5cTkVYGq/7FscoMmhI2xfjMuqth67bgw2FU6wqErkTlcqTHr++sEz2/t2ZEajqQyGZxETZ/YiTHPhYwPXUd24JHdp+txpSMd6y2IC8BZJxkyV6ZMyenSCkjyr+KUPkuDbAspTsZ23yHEMmniZCZEAswW0dBiY/yg8knkb4UPk=
  - AUTHOR_EMAIL=gambol99@gmail.com
  - REGISTRY_USERNAME=gambol99
  - REGISTRY=docker.io

services:
  - docker

language: go
go:
  - 1.6

install:
  - go get github.com/tools/godep
  - docker login -u ${REGISTRY_USERNAME} -p ${REGISTRY_TOKEN} -e ${AUTHOR_EMAIL} ${REGISTRY}

script:
  - make test
  - if [ "$TRAVIS_BRANCH" == "master" ]; then VERSION=latest make docker-release; fi
  - if [ -n "$TRAVIS_TAG" ]; then VERSION=$TRAVIS_TAG make docker-release; fi

